# Generated by Django 4.1.7 on 2023-05-16 12:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamas_ba_ma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='اسم')),
                ('text', models.TextField(null=True, verbose_name='متن')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('apdated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس های باما',
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(verbose_name='توضیحات شماره یک')),
                ('img', models.ImageField(upload_to='img', verbose_name='عکس کاور')),
                ('img2', models.ImageField(upload_to='img', verbose_name='عکس بدنه')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf', verbose_name='فایل PDF')),
                ('body2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات شماره دو')),
                ('Accepted', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('apdated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True, verbose_name='لینک صفحه رمان')),
                ('link_p', models.CharField(max_length=500, null=True, verbose_name='لینک دانلود اول')),
                ('link_d', models.CharField(max_length=500, null=True, verbose_name='لینک دانلود دوم')),
                ('eshtrak', models.BooleanField(default=False, verbose_name='اشتراک ویژه')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'رمان',
                'verbose_name_plural': 'رمان ها',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(verbose_name='توضیحات')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='عکس')),
                ('music', models.FileField(blank=True, null=True, upload_to='Music', verbose_name='فایل پادکست')),
                ('Accepted', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('apdated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True, verbose_name='لینک صفحه پادکست')),
                ('link_p', models.CharField(max_length=500, null=True, verbose_name='لینک پخش ')),
                ('link_d', models.CharField(max_length=500, null=True, verbose_name='لینک دانلود')),
                ('eshtrak', models.BooleanField(default=False, verbose_name='اشتراک ویژه')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پادکست',
                'verbose_name_plural': 'پادکست ها',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Part_roman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(verbose_name='متن رمان')),
                ('name', models.CharField(max_length=50, verbose_name='اسم پارت')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('apdated', models.DateField(auto_now=True)),
                ('roman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='رمان والد')),
            ],
            options={
                'verbose_name': 'پارت بندی رمان',
                'verbose_name_plural': 'پارت بندی رمان ها',
            },
        ),
        migrations.CreateModel(
            name='Part_pad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='متن پادکست')),
                ('name', models.CharField(max_length=50, verbose_name='اسم ')),
                ('link', models.CharField(max_length=1000, verbose_name='لینک رمان')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('apdated', models.DateField(auto_now=True)),
                ('pad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.podcast', verbose_name='پادکست والد')),
            ],
            options={
                'verbose_name': 'زیر مجموعه پادکست',
                'verbose_name_plural': 'زیر مجموعه پادکست ها',
            },
        ),
        migrations.CreateModel(
            name='Comments_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='کاربر')),
                ('text', models.TextField(null=True, verbose_name='متن')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('apdated', models.DateField(auto_now=True)),
                ('articel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post', verbose_name='رمان والد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riplay', to='post.comments_post', verbose_name='ریپلای')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامت رمان',
                'verbose_name_plural': 'کامنت های رمان',
            },
        ),
        migrations.CreateModel(
            name='Comments_Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='اسم')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('apdated', models.DateField(auto_now=True)),
                ('articel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.podcast', verbose_name='رمان والد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riplay', to='post.comments_podcast', verbose_name='ریپلای')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت پادکست',
                'verbose_name_plural': 'کامنت های پادکست',
            },
        ),
    ]
