# Generated by Django 4.1.7 on 2023-05-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
