# Generated by Django 4.1.7 on 2023-05-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='view',
            field=models.ImageField(default=1, upload_to='', verbose_name='بازدید'),
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.ImageField(default=1, upload_to='', verbose_name='بازدید'),
        ),
    ]
