# Generated by Django 4.1.7 on 2023-05-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_podcast_view_alter_post_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='view',
            field=models.IntegerField(default=1, verbose_name='بازدید'),
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=1, verbose_name='بازدید'),
        ),
    ]
