# Generated by Django 4.1.7 on 2023-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_podcast_apdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='correction',
            field=models.CharField(choices=[('1', 'عاشقانه'), ('2', 'ترسناک'), ('3', 'فانتزی'), ('4', 'کوتاه'), ('5', 'اجتماعی'), ('6', 'طنز'), ('7', 'پلیسی'), ('8', 'BDSM')], default=1, max_length=100, verbose_name='ژانر'),
            preserve_default=False,
        ),
    ]
