# Generated by Django 4.1.7 on 2023-05-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_podcast_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='لینک صفحه رمان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='لینک صفحه رمان'),
        ),
    ]
