# Generated by Django 4.1.7 on 2023-06-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_part_roman_a_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات عکس'),
        ),
        migrations.AddField(
            model_name='post',
            name='alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات عکس'),
        ),
    ]
