# Generated by Django 4.1.7 on 2023-06-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_podcast_alt_post_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='buy_rom',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
