# Generated by Django 4.1.7 on 2023-06-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_buy_rom'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='javyez',
            field=models.BooleanField(default=False, verbose_name='رمان جایزه دار'),
        ),
    ]
