# Generated by Django 4.2.5 on 2023-09-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_podcast_author_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Condition',
            field=models.CharField(blank=True, choices=[('1', 'به اتمام رسیده'), ('2', 'در حال ادامه')], max_length=100, null=True, verbose_name='وضغیت رمان'),
        ),
        migrations.AddField(
            model_name='post',
            name='imgProf',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس نویسنده'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='اسم نویسنده'),
        ),
    ]
