# Generated by Django 4.2.5 on 2023-09-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_post_condition_post_imgprof_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Condition',
            field=models.CharField(blank=True, choices=[('به اتمام رسیده', 'به اتمام رسیده'), ('در حال ادامه', 'در حال ادامه')], max_length=100, null=True, verbose_name='وضغیت رمان'),
        ),
    ]
