# Generated by Django 4.2.5 on 2023-09-26 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_post_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(auto_now_add=datetime.datetime(2023, 9, 26, 13, 41, 10, 325664, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
