# Generated by Django 4.2.5 on 2023-09-26 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_post',
            name='user_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین بودن کاربر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(auto_now_add=datetime.datetime(2023, 9, 26, 18, 18, 21, 500896, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
