# Generated by Django 4.2.5 on 2023-10-04 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_comments_post_user_admin_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(auto_now_add=datetime.datetime(2023, 10, 4, 9, 40, 7, 851197, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
