# Generated by Django 4.2.5 on 2023-10-20 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_podcast_botmodel_post_botmodel_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(auto_now_add=datetime.datetime(2023, 10, 20, 14, 40, 3, 730175, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
