# Generated by Django 4.2.5 on 2023-10-20 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(auto_now_add=datetime.datetime(2023, 10, 20, 15, 6, 17, 500161, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
