# Generated by Django 4.2.5 on 2023-10-21 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(auto_now_add=datetime.datetime(2023, 10, 21, 19, 13, 2, 573974, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
