# Generated by Django 4.2.5 on 2023-10-23 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0036_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(auto_now_add=datetime.datetime(2023, 10, 23, 16, 34, 28, 225852, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
