# Generated by Django 4.1.7 on 2023-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='عکس تبلیغ')),
                ('title', models.CharField(max_length=50, verbose_name='تایتل')),
                ('title_dokme', models.CharField(max_length=50, verbose_name='متن دکمه')),
                ('link', models.CharField(max_length=900, verbose_name='لینک تبلیغ')),
                ('crated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نبلیغات',
                'verbose_name_plural': 'تبلیغات ها',
            },
        ),
    ]
