# Generated by Django 4.1.7 on 2023-05-15 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hmtext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم کاربر')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='hmkari', verbose_name='فایل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'همکاری با ما',
                'verbose_name_plural': 'همکاری ها باما',
            },
        ),
    ]
