# Generated by Django 4.1.7 on 2023-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autherroman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('name', models.CharField(max_length=100, verbose_name='اسم کاربر')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='autherroman', verbose_name='عکس ارسالی')),
            ],
            options={
                'verbose_name': 'درخواست حذف رمان',
                'verbose_name_plural': 'درخواست های حذف رمان',
            },
        ),
    ]
