# Generated by Django 4.1.7 on 2023-06-12 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_advertise_id_fild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roman', models.CharField(max_length=150, verbose_name='رمان')),
                ('text', models.TextField()),
                ('bol', models.BooleanField(default=False, verbose_name='جواب درست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'جایزه',
                'verbose_name_plural': 'جوایز',
            },
        ),
    ]
