# Generated by Django 4.1.7 on 2023-06-17 08:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0013_post_javyez'),
        ('home', '0006_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJvayez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Condition', models.BooleanField(default=False, verbose_name=' شکرت کرده در مسابقات جوایز رمان')),
                ('roman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='رمان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شرکت کنند جوایز',
                'verbose_name_plural': 'شرکت کنندگان جوایز',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='سوالات رمان')),
                ('roman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='رمان')),
            ],
            options={
                'verbose_name': 'سوال رمان',
                'verbose_name_plural': 'سوالات رمان ها',
            },
        ),
    ]
