# Generated by Django 4.1.7 on 2023-06-24 12:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userjvayez_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='abutkarbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='اسم')),
                ('img', models.ImageField(upload_to='', verbose_name='عکس')),
                ('body', models.CharField(max_length=300, verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'عکس کارکنان',
                'verbose_name_plural': 'عکس های کارکنان',
            },
        ),
        migrations.CreateModel(
            name='abutsaznde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='اسم')),
                ('title', models.CharField(max_length=300, verbose_name='متن')),
                ('img', models.ImageField(upload_to='', verbose_name='عکس')),
                ('body', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'عکس مالک',
                'verbose_name_plural': 'عکس های مالک',
            },
        ),
    ]
