# Generated by Django 4.1.7 on 2023-06-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoont', '0002_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coment_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین کامنت ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='part',
            field=models.BooleanField(default=False, verbose_name='ادمین پارت بندی ها'),
        ),
        migrations.AddField(
            model_name='user',
            name='roman_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین رمان ها'),
        ),
    ]
