# Generated by Django 4.1.7 on 2023-06-27 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acoont', '0003_user_coment_admin_user_part_user_roman_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kole_part', models.IntegerField(verbose_name='کل پارت های  گذاشته شده')),
                ('padakt_part', models.IntegerField(blank=True, default=0, null=True, verbose_name='پارت های پرداخت شده')),
                ('bki_part', models.IntegerField(blank=True, default=0, null=True, verbose_name='پارت های پرداخت نشده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تعداد پارت کاربر',
                'verbose_name_plural': 'تعداد پارت های کاربران',
            },
        ),
    ]
