# Generated by Django 4.2.5 on 2023-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoont', '0004_user_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/prof', verbose_name='عکس'),
        ),
    ]
