# Generated by Django 4.2.5 on 2023-09-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoont', '0005_user_buo_user_email_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/media/img/prof/tn_1669054743_8788_15311.jpg', null=True, upload_to='img/prof', verbose_name='عکس'),
        ),
    ]
