# Generated by Django 4.2.5 on 2023-09-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoont', '0009_user_airbnb_user_facebook_user_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/prof', verbose_name='عکس'),
        ),
    ]
