# Generated by Django 4.2.5 on 2023-10-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoont', '0010_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='https://ako.storage.iran.liara.space/userAvatar.png', null=True, upload_to='img/prof', verbose_name='عکس'),
        ),
    ]
