# Generated by Django 4.2.5 on 2023-10-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoont', '0011_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/prof', verbose_name='عکس'),
        ),
    ]
