# Generated by Django 4.2.5 on 2023-10-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='FilmModel',
        ),
    ]
