# Generated by Django 4.2.5 on 2023-10-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='zerfilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('link', models.URLField(verbose_name='لینک فیلم')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.filmmodel', verbose_name='زیر مجموعه')),
            ],
            options={
                'verbose_name': 'اموزش نویسندگی',
                'verbose_name_plural': 'اموزش های نویسندگی',
            },
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
