# Generated by Django 4.2.5 on 2023-10-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_zerfilm_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zerfilm',
            options={'verbose_name': 'قسمت اموزش', 'verbose_name_plural': 'قسمت های اموزش'},
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
