# Generated by Django 4.2.5 on 2023-10-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_alter_zerfilm_options_filmmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerfilm',
            name='a_id',
            field=models.IntegerField(default=0, verbose_name='قسمت بندی اموزش ها'),
        ),
    ]
