# Generated by Django 4.2.5 on 2023-10-23 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0006_zerfilm_a_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='کاربر')),
                ('text', models.TextField(null=True, verbose_name='متن')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('apdated', models.DateField(auto_now=True)),
                ('articel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='film.filmmodel', verbose_name='اموزش والد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film.comments_film', verbose_name='ریپلای')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامت آموزش',
                'verbose_name_plural': 'کامنت های آموزش',
            },
        ),
    ]
