# Generated by Django 4.2.5 on 2023-10-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_comments_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_film',
            name='user_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین بودن کاربر'),
        ),
    ]
