# Generated by Django 4.2.5 on 2023-10-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_comments_film_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_film',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riplay', to='film.comments_film', verbose_name='ریپلای'),
        ),
    ]
